services:
  - type: web
    name: anime-hub
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn anime_hub.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0