# Generated by Django 6.0.7 on 2026-07-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('calificacion', models.FloatField(default=0.0)),
            ],
        ),
    ]
