# Generated by Django 6.0.7 on 2026-07-26 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='animes_favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anime',
            name='vistos',
            field=models.ManyToManyField(blank=True, related_name='animes_vistos', to=settings.AUTH_USER_MODEL),
        ),
    ]
