# Generated by Django 6.0.7 on 2026-07-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_anime_favoritos_anime_vistos'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Enlace URL de la imagen de portada', max_length=500, null=True),
        ),
    ]
