# Generated by Django 6.0.7 on 2026-07-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_anime_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='URL de YouTube (ej. https://www.youtube.com/embed/...)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número del episodio (ej. 1)')),
                ('titulo', models.CharField(help_text='Título del episodio', max_length=200)),
                ('video_url', models.URLField(help_text='Enlace del video o Embed Code', max_length=700)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='catalog.anime')),
            ],
        ),
    ]
