# Generated by Django 6.0.7 on 2026-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_anime_trailer_url_alter_anime_imagen_url_episodio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodio',
            options={'ordering': ['numero']},
        ),
        migrations.AlterField(
            model_name='anime',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Enlace URL de la imagen de portada', max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='episodio',
            constraint=models.UniqueConstraint(fields=('anime', 'numero'), name='unique_episodio_por_anime'),
        ),
    ]
